openapi: 3.1.0
info:
  title: Sentry-for-AI API
  version: 1.0.0
  description: |
    Core REST API for AI Observability Platform.
servers:
  - url: https://api.sentryai.dev

paths:
  /v1/projects:
    post:
      summary: Create new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '200':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    get:
      summary: List user projects
      responses:
        '200':
          description: Project list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

  /v1/events:
    post:
      summary: Ingest AI event (trace, log, eval, token usage, etc.)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventIngestRequest'
      responses:
        '200':
          description: Ingested

  /v1/traces/{traceId}:
    get:
      summary: Fetch a full AI trace tree
      parameters:
        - $ref: '#/components/parameters/TraceId'
      responses:
        '200':
          description: Trace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trace'

  /v1/evals/run:
    post:
      summary: Trigger eval suite on a model or app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvalRunRequest'
      responses:
        '200':
          description: Eval job started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvalJob'

components:
  parameters:
    TraceId:
      name: traceId
      in: path
      required: true
      schema:
        type: string

  schemas:
    CreateProjectRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
        tier:
          type: string
          enum: [free, pro, scale]

    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        apiKey:
          type: string

    EventIngestRequest:
      type: object
      properties:
        projectId:
          type: string
        type:
          type: string
          enum: [log, error, span, message, token_usage, eval_metric]
        timestamp:
          type: string
          format: date-time
        data:
          type: object
        metadata:
          type: object

    Trace:
      type: object
      properties:
        traceId:
          type: string
        projectId:
          type: string
        spans:
          type: array
          items:
            $ref: '#/components/schemas/Span'

    Span:
      type: object
      properties:
        id:
          type: string
        parentId:
          type: string
        name:
          type: string
        start:
          type: string
        end:
          type: string
        model:
          type: string
        prompt:
          type: string
        response:
          type: string
        tokenUsage:
          type: object
          properties:
            input:
              type: number
            output:
              type: number

    EvalRunRequest:
      type: object
      properties:
        projectId:
          type: string
        suiteId:
          type: string
        model:
          type: string
        datasetId:
          type: string

    EvalJob:
      type: object
      properties:
        jobId:
          type: string
        projectId:
          type: string
        status:
          type: string
          enum: [queued, running, completed, failed]
